version: '3'
services:
  app:
    container_name: app
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    ports:
      - '8888:8080'
    profiles:
      - prod
    networks:
      - spring-cloud-network

  db:
    container_name: postgersql
    image: 'postgres:13.1-alpine'
    restart: on-failure
    ports:
      - '5438:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - spring-cloud-network

networks:
  spring-cloud-network:
    driver: bridge