spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:postgresql://localhost:5438/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres

  sql:
    init:
      platform: postgres

server:
  port: 8181