spring:
  profiles:
    active: prod

  redis:
    port: 6688
    host: localhost

logging:
  file:
    name: logs/logs.log

security:
  jwt:
    token:
      secret-key: YOUR_SECRET_KEY
      expire-length: 3600000 # 1h
